server:
  port: 8091

spring:
  datasource:
    username: root
    password: yaowenyang
    url: jdbc:mysql://127.0.0.1:3306/demo01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/

mybatis:
  mapper-locations: classpath:/mapper/*.xml



